### ISSUE TITLE
Document how to write tests with cassettes

### ISSUE THREAD

**Issue by morgoth** [morgoth/picasa#28]

**Comment by morgoth** [comment]
since Picasa service will retire, there is no need for this I guess.

**Comment by jylitalo** [comment]
Even if they will replace Picasa with Google Photos as a brand name, it doesn't mean that API wouldn't stay available. At least, I haven't yet heard that their would be new API for Google Photos.
I guess I am just hoping that if someone has link to Google Photos API, they would post a link :)
