### ISSUE TITLE
user_id password pairs have been deprecated :(

### ISSUE THREAD

**Issue by jylitalo** [morgoth/picasa#34]
It seems that good old user_id password pair is no longer valid option. 
Yesterday I tried to use it (after few weeks pause) and stumbled on URL that led me announcement that application passwords have been deprecated and we should all now use OAuth2.

**Comment by jylitalo** [comment]
https://developers.google.com/oauthplayground/ seems to be easist way to generate access_token that is valid for one hour.

**Comment by morgoth** [comment]
Thanks, indeed. I'll look into it

**Comment by morgoth** [comment]
I removed support for passing `password` and added a hint how to obtain `access_token` for one time usage https://github.com/morgoth/picasa/commit/3e88138207b45a19867c88669556ba738fe8c1da

Integration with OAuth2 is a much bigger task.
