### ISSUE TITLE
redirect_uri_mismatch 

### ISSUE THREAD

**Issue by yuraksisa** [morgoth/picasa#39]
I've followed the steps to get the refresh_token and I'm getting redirect_uri_mismatch

require "signet/oauth_2/client"
signet = Signet::OAuth2::Client.new(
  code: code,
  token_credential_uri: "https://www.googleapis.com/oauth2/v3/token",
  client_id: client_id,
  client_secret: client_secret,
  redirect_uri: "urn:ietf:wg:oauth:2.0:oob",
)
signet.fetch_access_token!

{
 "error": "redirect_uri_mismatch",
 "error_description": "Bad Request"
}

**Comment by morgoth** [comment]
I just checked and it worked fine for me.
Looks like redirect_uri which is "urn:ietf:wg:oauth:2.0:oob" here looks different in your settings?
Not sure if this is some unique value based on account, but you can check this when downloading JSON with credentials - you'll find it in the same place where cliend id and client secret is.

**Comment by yuraksisa** [comment]
Thank you for answering so quickly.

I've downloaded JSON with credentials. This is the result. It looks like that the redirect uris are ok. Is it possible it takes the service to be enabled?

{"installed":{"client_id":"MY-CLIENT_ID","project_id":"MY-PROJECT","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"MY-CLIENT-SECRET","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}

**Comment by morgoth** [comment]
I have no idea. I found this thread http://stackoverflow.com/questions/11485271/google-oauth-2-authorization-error-redirect-uri-mismatch but not sure what's wrong. Your JSON looks pretty the same as mine.

**Comment by yuraksisa** [comment]
It's working. The problem was in the URL I used to get the authorization code

I used the redirect_uri=**urn:ietf:wg:oauth:2.0:oob:auto** and I should use the same uri when I accessed to get the refresh token or just use **urn:ietf:wg:oauth:2.0:oob** in both requests

https://accounts.google.com/o/oauth2/auth?scope=http://picasaweb.google.com/data/&redirect_uri=**urn:ietf:wg:oauth:2.0:oob:auto**&response_type=code&client_id=MY_CLIENT_ID
