### ISSUE TITLE
Can I use this lib to check photo status?

### ISSUE THREAD

**Issue by stefanov-stefan** [morgoth/picasa#40]
Common issue with the new uploader is that it does not upload all photos and it doesn't provide information what was not uploaded. The google photos backup uploader tool has a hidden File Status command (https://sites.google.com/site/picasaresources/Home/Picasa-FAQ/g-auto-backup-for-desktop/how-tos/how-to-check-why-a-picture-isn-t-being-uploaded?pli=1) I was wondering whether using this API we can get access to such command as well, so we can check file by file.

**Comment by morgoth** [comment]
I don't think so. You can just fetch whole album of photos and check if all files are there comparing to your locale ones.

**Comment by stefanov-stefan** [comment]
I have no albums, can I download all files at.least?

Sent from my Samsung device

-------- Original message --------

**Comment by morgoth** [comment]
I think it's not possible to have photos without album on picasa API. Google recently deprecated picasa service and they don't provide API for their google photos, as far as I know.
Not sure how to integrate with their recent changes.

**Comment by stefanov-stefan** [comment]
Thanks

Sent from my Samsung device

-------- Original message --------
