### ISSUE TITLE
accessing google photos

### ISSUE THREAD

**Issue by ciapecki** [morgoth/picasa#42]
I know picasa was deprecated but this gem works fine with archived albums.
New albums created under photos.google.com get different links to access them and this gem won't show them.

I just wanted to ask if there is maybe a different way to access albums newly created in Google Photos. Any gem?

**Comment by morgoth** [comment]
I can't see anything in the google official tooling https://github.com/googleapis/google-api-ruby-client/tree/master/generated/google/apis also don't know any other gem
